### ISSUE TITLE
Cactbot config toggles?

### ISSUE THREAD

**Issue by calmcacil** [joshua-software-dev/LMeter#5]
Any plans to implement config toggles, swapping between TTS sounds and such, or just having a toggle to show cactbots config screen?

**Comment by joshua-software-dev** [comment]
At the moment the bottleneck on this is that I uh, didn't know Cactbot had a settings menu, and that I don't have a windows machine with a graphics card I can use see what all the settings are in normal ACT to see how feasible it is to implement a good settings menu.

I'd like to have these options integrated somehow however, even if its just a crappy config file you can set the options in manually (although I'd really like to do something better). I'll look into this though, no ETA however.

**Comment by calmcacil** [comment]
sorry, my bad, its probably wrong to call it a settings menu, its a separate overlay that sets the settings for the overlay. (http://proxy.iinact.com/overlay/cactbot/ui/config/config.html) with browsingway you can set it (toggle tts etc) by simply loading up that overlay.
